as yet unclassified
defaultPlugins

	^ {
	SpotlightPeriscopePlugin.
ToolsPeriscopePlugin.
BookmarksPeriscopePlugin.
BehaviorReferencesPeriscopePlugin.
TimeStampPeriscopePlugin.
ShowImplementationPeriscopePlugin.

"BookmarksPeriscopePlugin."
"BookmarksPeriscopePlugin."
	"	ShowImplementationPeriscopePlugin.
		TimeStampPeriscopePlugin.
		BehaviorReferencesPeriscopePlugin. 
		BookmarksPeriscopePlugin.
		ToolsPeriscopePlugin.
		SpotlightPeriscopePlugin"
	   } asOrderedCollection